local_backend: true

backend:
  name: github
  repo: raylee30/media-dental
  branch: main
  base_url: https://www.mjsmiles.com
  auth_endpoint: oauth

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "settings"
    label: "Website Content"
    files:
      - name: "home"
        label: "Home Page"
        file: "src/_data/home.json"
        format: "json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "text"
          - label: "Hero Image"
            name: "hero_image"
            widget: "image"
